# 2. Numpy a a maticové operácie

In [1]:
import numpy as np
import math

Na vytvorenie matice v Pythone použijeme knižnicu numpy.

In [2]:
A = np.array([[1, 2], [3, 4]])
print("Matrix/ Matica: \n", A)

Matrix/ Matica: 
 [[1 2]
 [3 4]]


In [5]:
v_row = np.array([1, 2, 3, 4])
print("Row vector / Riadkovy vektor: ", v_row)

Row vector / Riadkovy vektor:  [1 2 3 4]


Stĺpcovy vektor dostaneme jednoduchou úpravou (transpose) riadkového vektora. 

In [6]:
v_column = np.array([[1, 2, 3, 4]]).T
print("Column vector / Stlpcovy vektor: ", v_column)

Column vector / Stlpcovy vektor:  [[1]
 [2]
 [3]
 [4]]


In [7]:
trans_2_v_row = v_column.T
print("Transpose / Transponuje sa cez atribut T (Vymena riadkov a stlpcov): ", trans_2_v_row)

Transpose / Transponuje sa cez atribut T (Vymena riadkov a stlpcov):  [[1 2 3 4]]


In [8]:
lin_spaced_vector = np.linspace(0, 9, 10)
print("Linearly spaced vector / Vektor s linearnym rastom:", lin_spaced_vector)

Linearly spaced vector / Vektor s linearnym rastom: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [9]:
v_empty = np.array([])
print("Empty vector / Prazdny vector: ", v_empty)

Empty vector / Prazdny vector:  []


# Specific types of initialization:

In [13]:
mat_zeros = np.zeros((3, 3))  # tuple as input param
print(mat_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
mat_ones = np.ones((2, 3, 2))
print("Ones matrix: \n", mat_ones)

Ones matrix: 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [15]:
mat_eye = np.eye(3)
print("Diagional matrix / Diagonalna matica:\n", mat_eye)

Diagional matrix / Diagonalna matica:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
mat_rand = np.random.rand(2, 3)
print("Random matrix / Matica nahodnych cisel:\n", mat_rand)

Random matrix / Matica nahodnych cisel:
 [[0.08734978 0.23042717 0.24487559]
 [0.6776393  0.50266768 0.01242037]]


In [17]:
vec = np.array([3, 2, 1])
print("Third element of the vector / Treti prvok vektora: ", vec[2])

Third element of the vector / Treti prvok vektora:  1


# Pristup k matici:

In [19]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Acessing matrix / Pristup k matici")

Acessing matrix / Pristup k matici


In [58]:
print("Accessing  element at (2,3) / Pristup k elementu (2,3)", mat[1][2])
print("Accesing different elements through sequences:/ Dynamicky pristup k elementom matic")
print(mat[0][:])  # vrati prvy riadok ako riadkovy vektor
print("")
print(mat[:][1])  # vrati druhy stlpec ako riadkovy vektor !!!
print("")
print(mat[1:3, 1:3])  # submatica zacinajuca na 2,2
print("")
print(mat[1:, 1:])  # (2,2) + till end
print("")
print(mat[:3, :3])  # od [] -> to index [3 3]

Accessing  element at (2,3) / Pristup k elementu (2,3) 6
Accesing different elements through sequences:/ Dynamicky pristup k elementom matic
[1 2 3]

[4 5 6]

[[5 6]]

[[5 6]]

[[1 2 3]
 [4 5 6]]


In [21]:
print("Shape of the matrix/ Rozmery matice: ", mat.shape)
print("Shape of the matrix/ Rozmery matice: ", mat.shape[0])
print("Shape of the matrix/ Rozmery matice: ", mat.shape[1])

Shape of the matrix/ Rozmery matice:  (3, 3)
Shape of the matrix/ Rozmery matice:  3
Shape of the matrix/ Rozmery matice:  3


In [22]:
# Jednoduché operácie s vektormi a maticam:

In [45]:
vec_a = np.array([[1, 2, 3, 4]]).T
print(2 * vec_a)
print("")
print(vec_a / 2)
print("")
print(vec_a ** 3)

[[2]
 [4]
 [6]
 [8]]

[[0.5]
 [1. ]
 [1.5]
 [2. ]]

[[ 1]
 [ 8]
 [27]
 [64]]


In [24]:
vec_b = np.array([[1, 2, 3, 4]]).T

In [46]:
print(vec_a * vec_b)
print("")
print(vec_a / vec_b)
print("")
print(vec_a - vec_b)
print("")
print(np.log(vec_a))
print("")
print(np.round(np.log(vec_a)))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]
 [16 20 24]]

[[0.25       0.2        0.16666667]
 [0.5        0.4        0.33333333]
 [0.75       0.6        0.5       ]
 [1.         0.8        0.66666667]]

[[-3 -4 -5]
 [-2 -3 -4]
 [-1 -2 -3]
 [ 0 -1 -2]]

[[0.        ]
 [0.69314718]
 [1.09861229]
 [1.38629436]]

[[0.]
 [1.]
 [1.]
 [1.]]


 # Skalarne operacie na vektore -> vystup je skalar:

In [47]:
print(np.sum(vec_a))
print("")
print(np.mean(vec_a))
print("")
print(np.var(vec_a))
print("")
print(np.std(vec_a))
print("")
print(np.min(vec_a), np.max(vec_a))

10

2.5

1.25

1.118033988749895

1 4


# Operacie na matici -> vystup je vektor:

In [69]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(mat, 0))
print("Max of mat along axis 0: ", np.max(mat, 0))
print("Max of mat alojng axis 1: ", np.max(mat, 1))
print(np.max(mat))
print(mat[0] * mat[1])  # elementwise
print(mat[0].T * mat[1])    # vektorovy sucin
print(mat[0] * mat[1].T)  # vektorovy sucin
print(mat[0].T @ mat[1])  # skalarny sucin

[2.5 3.5 4.5]
Max of mat along axis 0:  [4 5 6]
Max of mat alojng axis 1:  [3 6]
6
[ 4 10 18]
[ 4 10 18]
[ 4 10 18]
32


# Operacie na matici:

In [55]:
mat_1 = np.random.rand(3, 2)
mat_2 = np.random.rand(2, 4)
vec_1 = np.array([[1, 2, 3]]).T
vec_2 = np.array([1, 2])
print(np.matmul(mat_1, mat_2))

[[0.13719749 0.43364034 1.02368693 0.23619351]
 [0.08422505 0.28631881 0.58398595 0.12513608]
 [0.0751601  0.22568294 0.58705273 0.14112276]]


In [32]:
print(np.matmul(vec_1.T, mat_1)) # 1x3 * 3x2 = 1x2
print(np.matmul(mat_1, vec_2)) # 3x2 * 2x1 = 3x1

[[5.0767014 3.5976351]]
[2.0338973  1.05757507 2.70764139]


In [33]:
print("Inverse matrix: \n", np.linalg.inv(np.random.rand(3, 3)))

Inverse matrix: 
 [[ -6.1196731   -1.05866526   4.99101161]
 [ -1.26162257  -1.51242049   2.35533199]
 [ 13.45026217   5.96535816 -11.017798  ]]


In [34]:
print("Eigen values: \n", np.linalg.eigvals(np.random.rand(3, 3)))

Eigen values: 
 [ 0.99111067  0.35678349 -0.15870386]


# Linearna algebra:

In [37]:
V, D = np.linalg.eig(np.random.rand(3, 3))
print("Eigen values: \n",V,"\n Eigen matrix\n",D)

Eigen values: 
 [ 1.14956327  0.19471947 -0.37881051] 
 Eigen matrix
 [[-0.18940084 -0.44777338  0.35604689]
 [-0.66885163 -0.57436542 -0.89060718]
 [-0.71886356  0.68527612  0.28293013]]


In [38]:
U, S, V = np.linalg.svd(np.random.rand(3, 3))
print("SVD single value decomposition: \n", U,"\n Eigen matrix\n",S,"\n Eigen matrix\n",V) # a = U * S * V'

SVD single value decomposition: 
 [[-0.30632573  0.42381257 -0.85237753]
 [-0.73596161 -0.67336191 -0.0703154 ]
 [-0.60375911  0.60577772  0.51817786]] 
 Eigen matrix
 [1.3162127  0.31975246 0.08358809] 
 Eigen matrix
 [[-0.26796134 -0.92365469 -0.27396849]
 [ 0.63446556  0.04481734 -0.77165074]
 [-0.72501736  0.38059614 -0.57401777]]


In [ ]:
B = np.random.rand(4, 4)
np.linalg.det(B)
np.sum(B)
print(B.reshape((8,2)))
vec_a = np.array([[1, 2, 3]])
vec_b = np.array([[4, 5, 6]])

In [ ]:
vec_c = np.concatenate((vec_a, vec_b), 0)
print(vec_c)

In [41]:
vec_c = np.array((vec_a, vec_b))
vec_c = np.squeeze(vec_c)
print(vec_c)

[[1 2 3]
 [4 5 6]]


In [42]:
print(np.repeat(A, 2,axis=0))
print(np.diag(B))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[0.09177902 0.92564961 0.49698464 0.56559653]
