# 2. Numpy a a maticové operácie

In [1]:
import numpy as np
import math

Na vytvorenie matice v Pythone použijeme knižnicu numpy.

In [2]:
A = np.array([[1, 2], [3, 4]])

Matrix/ Matica: [[1 2]
 [3 4]]
 
Maticu sme zadefinovali pomocou dvoch vektorov [1,2] a [3,4] 

In [3]:
v_row = np.array([1, 2, 3, 4])

Row vector / Riadkovy vektor:  [1 2 3 4]


In [4]:
v_column = np.array([[1, 2, 3, 4]]).T

Stĺpcovy vektor dostaneme jednoduchou úpravou (transpose) riadkového vektora.

Column vector / Stlpcovy vektor:  [[1]
[2]
[3]
[4]]

In [5]:
trans_2_v_row = v_column.T

Transpose / Transponuje sa cez atribut T (Vymena riadkov a stlpcov):  [[1 2 3 4]]

In [6]:
lin_spaced_vector = np.linspace(0, 9, 10)

Operacia linspace vrati x prvkov (10) od pociatku 0 po cislo 9. Tieto prvky su rovnomerne rozmiestnene cez dany interval (0-9)

Linearly spaced vector / Vektor s linearnym rastom: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

In [7]:
v_empty = np.array([])

Empty vector / Prazdny vector:  []

# Špeciálne inicializácie matíc:

In [8]:
mat_zeros = np.zeros((3, 3))  # tuple as input param
print(mat_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Operacia np.zeros vrati maticu s danym rozmerom, ktora je vyplnena nulami

In [9]:
mat_ones = np.ones((2, 3, 2))
print("Ones matrix: \n", mat_ones)

Ones matrix: 
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


Podobna operacia je np.ones, ktora ale vracia maticu vyplnenu jednotkami.

In [10]:
mat_eye = np.eye(3)
print("Diagional matrix / Diagonalna matica:\n", mat_eye)

Diagional matrix / Diagonalna matica:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Np.eye vrati diagonalnu maticu s danym rozmerom.

In [11]:
mat_rand = np.random.rand(2, 3)
print("Random matrix / Matica nahodnych cisel:\n", mat_rand)

Random matrix / Matica nahodnych cisel:
 [[0.40343779 0.67785879 0.98585484]
 [0.27987432 0.75698085 0.01405531]]


Pri vytvoreni nahdonych matic si mozeme pomoct kniznicou random pomocou ktorej si vieme priamo vytvorit maticu s danym rozmerom naplnenu nahodnymi cislami. 

In [12]:
vec = np.array([3, 2, 1])
print(vec[2])

1


Pri vybere specifickeho prvka z vektora alebo matice pracujeme s indexom. Nesmieme zabudnut, ze v pythone sa indexuje od 0.

# Pristup k matici:

In [13]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Acessing matrix / Pristup k matici")
print(mat)

Acessing matrix / Pristup k matici
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#print("Accessing  element at (2,3) / Pristup k elementu (2,3)", mat[1][2])
#print("Accesing different elements through sequences:/ Dynamicky pristup k elementom matic")
#print(mat[0][:])  # vrati prvy riadok ako riadkovy vektor
#print("")
#print(mat[:][1])  # vrati druhy stlpec ako riadkovy vektor !!!
#print("")
#print(mat[1:3, 1:3])  # submatica zacinajuca na 2,2
#print("")
#print(mat[1:, 1:])  # (2,2) + till end
#print("")
#print(mat[:3, :3])  # od [] -> to index [3 3]

Z matice vieme vybrat samostatne stlpce alebo riadky pomocou roznych indexov. Ak chceme vypisat prvy riadok matice ako riadkovy vektor pouzijeme mat[0][:]  co nam vrati vystup [1 2 3]
Obdobne to funguje pri vybere stlpca, kde indexy vymenime mat[:][1] : [4 5 6]

Jednotlive prikazy si mozete vyskusat v okne vyssie.

In [15]:
print("Shape of the matrix/ Rozmery matice: ", mat.shape)
print("Shape of the matrix/ Rozmery matice: ", mat.shape[0])
print("Shape of the matrix/ Rozmery matice: ", mat.shape[1])

Shape of the matrix/ Rozmery matice:  (3, 3)
Shape of the matrix/ Rozmery matice:  3
Shape of the matrix/ Rozmery matice:  3


In [16]:
# Jednoduché operácie s vektormi a maticam:

S maticami mozeme vykonavat rozne vypoctove operacie od scitania a odcitania po SVD dekompoziciu. Vsetky operacie su sprostredkovane kniznicou Numpy.

In [17]:
vec_a = np.array([[1, 2, 3, 4]]).T
print(vec_a)

[[1]
 [2]
 [3]
 [4]]


In [18]:
vec_b = np.array([[1, 2, 3, 4]]).T
print(vec_b)

[[1]
 [2]
 [3]
 [4]]


In [19]:
#print(2 * vec_a)
#print("")
#print(vec_a / 2)
#print("")
#print(vec_a ** 3)

#print(vec_a * vec_b)
#print("")
#print(vec_a / vec_b)
#print("")
#print(vec_a - vec_b)
#print("")
#print(np.log(vec_a))
#print("")
#print(np.round(np.log(vec_a)))

 # Skalarne operacie na vektore -> vystup je skalar:

Nasledujuce prikazy nam vratia uzitocne informacie o matici na ktoru boli pouzite. 

-Operacia sum nam vrati sucet vsetkych prvkov v matici

-Operacia mean vyrata aritmeticky priemer na specifikovanej osi. Ak sme os nespecifikovali tak sa vyrata priemer vsetkych prvkov.

-Var nam vrati rozptyl prvkov v matici. 

-Std vyrata smerodajnu odchylku.

-Operacie np.min a np.max vratia najmensi a najväcsi prvok v matici

In [20]:
print(np.sum(vec_a))
print("")
print(np.mean(vec_a))
print("")
print(np.var(vec_a))
print("")
print(np.std(vec_a))
print("")
print(np.min(vec_a), np.max(vec_a))

10

2.5

1.25

1.118033988749895

1 4


# Operacie na matici -> vystup je vektor:

Velmi dolezitymi operaciami s maticami su vypocty skalarnych a vektorovych sucinov. Tieto operacie si je potrebne osvojit a vediet sa orientovat v roznych zapisoch.

In [21]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
#print(np.mean(mat, 0))
#print("Max of mat along axis 0: ", np.max(mat, 0))
#print("Max of mat alojng axis 1: ", np.max(mat, 1))
#print(np.max(mat))
#print(mat[0] * mat[1])  # elementwise
#print(mat[0].T * mat[1])    # vektorovy sucin
#print(mat[0] * mat[1].T)  # vektorovy sucin
#print(mat[0].T @ mat[1])  # skalarny sucin

# Operacie na matici:

In [22]:
mat_1 = np.random.rand(3, 2)
mat_2 = np.random.rand(2, 4)
vec_1 = np.array([[1, 2, 3]]).T
vec_2 = np.array([1, 2])
#print(np.matmul(mat_1, mat_2))

In [23]:
#print(np.matmul(vec_1.T, mat_1)) # 1x3 * 3x2 = 1x2
#print(np.matmul(mat_1, vec_2)) # 3x2 * 2x1 = 3x1

In [24]:
#print("Inverse matrix: \n", np.linalg.inv(np.random.rand(3, 3)))

In [25]:
#print("Eigen values: \n", np.linalg.eigvals(np.random.rand(3, 3)))

# Linearna algebra:

In [26]:
V, D = np.linalg.eig(np.random.rand(3, 3))
print("Eigen values: \n",V,"\n Eigen matrix\n",D)

Eigen values: 
 [1.23638316 0.43417129 0.01201218] 
 Eigen matrix
 [[-0.08433031 -0.62897725 -0.34588098]
 [-0.95695945  0.76109156 -0.39536061]
 [-0.2776995  -0.15851578  0.850915  ]]


In [27]:
U, S, V = np.linalg.svd(np.random.rand(3, 3))
print("SVD single value decomposition: \n", U,"\n Eigen matrix\n",S,"\n Eigen matrix\n",V) # a = U * S * V'

SVD single value decomposition: 
 [[-0.50475886  0.86283199  0.02719278]
 [-0.71160683 -0.39804595 -0.57894313]
 [-0.48870668 -0.31157724  0.81491435]] 
 Eigen matrix
 [1.84402584 0.53036126 0.47574497] 
 Eigen matrix
 [[-0.71443827 -0.54048218 -0.4443613 ]
 [ 0.55778164 -0.82336123  0.10467051]
 [ 0.42244241  0.17307596 -0.88971182]]


In [28]:
B = np.random.rand(4, 4)
np.linalg.det(B)
np.sum(B)
print(B.reshape((8,2)))
vec_a = np.array([[1, 2, 3]])
vec_b = np.array([[4, 5, 6]])

[[0.32606342 0.89051006]
 [0.53351575 0.91198193]
 [0.88005695 0.21590958]
 [0.25623601 0.84964013]
 [0.98817016 0.01050342]
 [0.55545406 0.22084121]
 [0.39058538 0.74963682]
 [0.81521112 0.34429125]]


In [29]:
vec_c = np.concatenate((vec_a, vec_b), 0)
#print(vec_c)
vec_c = np.array((vec_a, vec_b))
vec_c = np.squeeze(vec_c)
#print(vec_c)

Concatenate spoji dve matice pozdlz danej osi.
Prikaz squeeze odstrani z matice osy s rozmerom 1.

In [30]:
print(A)
print("")
print(np.repeat(A, 2,axis=0))
print("")
print(np.diag(B))

[[1 2]
 [3 4]]

[[1 2]
 [1 2]
 [3 4]
 [3 4]]

[0.32606342 0.21590958 0.55545406 0.34429125]


Operacia repeat opakuje prvky matice. Pocet opakovani si zvolime my, tak isto aj os pozdlz ktorej sa prvky duplikuju. 
Nasledne vykoname operaciu diag, ktora nam vypise z danej matice len tie prvky, ktore lezia na hlavnej diagonale.